version: '2'
services:
        web:
            build: store_rest_api/.
            ports:
                - "5000:5000"
            links:
                - db
            hostname: web
            restart: always
            networks:
                - web
            depends_on: 
                - db
                
        db:
            image: mariadb:10.1
            environment:
                MYSQL_ROOT_PASSWORD: secret-password
                MYSQL_DATABASE: db
                MYSQL_USER: root
                MYSQL_PASSWORD: secret-password
            ports:
                - "3306:3306"
            hostname: db
            networks:
                - web
            restart: always
networks:
  web:
    external:
      name: web-network

